spring:
  application:
    name: api-financas
  profiles:
    active: developer

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enable: true
    app:
      name: "Api de Finanças"
      version: 1.0.0
      description: "Api responsável por gerenciar financas"
    metrics:
      tags:
        application: api-financas
  metrics:
    enable:
      all: true

  springdoc:
    show-actuator: true
    swagger-ui:
      path: /
    api-docs:
      path: /v3/api-docs
